In [85]:
import numpy
import scipy

In [86]:
class NeuralNetwork:

    # Initialise the neural network
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
        self.learning_rate = learning_rate

        # Init the weights - 0.5 that for minus values
        self.weight_input_hidden = (numpy.random.rand(self.hidden_nodes, self.input_nodes) - 0.5)
        self.weight_hidden_output = (numpy.random.rand(self.output_nodes, self.hidden_nodes) - 0.5)

        # Activation function is sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)

    # Train the network
    def train():
        pass

    # Query the neural network
    def query(self, input_list):

        # Convert input list to 2d array (column vector)
        inputs = numpy.array(input_list, ndmin=2).T

        # First layer
        hidden_inputs = numpy.dot(self.weight_input_hidden, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)

        # Second layer
        final_inputs = numpy.dot(self.weight_hidden_output, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)

        return final_outputs



    def describe(self):
        print(f'3 layer neural network with {self.input_nodes} input nodes / {self.hidden_nodes} hidden nodes / {self.output_nodes} output nodes and learning rate {self.learning_rate}')


In [87]:
n = NeuralNetwork(3,4,1,0.3)
n.describe()

3 layer neural network with 3 input nodes / 4 hidden nodes / 1 output nodes and learning rate 0.3
[[ 0.03747072 -0.35113439  0.16526144]
 [ 0.24070521 -0.32807632 -0.4219592 ]
 [ 0.27612155  0.43760489  0.03932515]
 [ 0.23113425  0.33311705  0.2392056 ]] 
 [[-1.15649842e-01 -2.74668012e-04  3.17076450e-01 -2.00613486e-01]]


In [88]:
n.query([1,2,3])

array([[0.50679766]])