In [57]:
import numpy

In [58]:
class NeuralNetwork:

    # Initialise the neural network
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
        self.learning_rate = learning_rate

        # Init the weights - 0.5 that for minus values
        self.weight_input_hidden = (numpy.random.rand(self.hidden_nodes, self.input_nodes) - 0.5)
        self.weight_hidden_output = (numpy.random.rand(self.output_nodes, self.hidden_nodes) - 0.5)

    # Train the network
    def train():
        pass

    # Query the neural network
    def query():
        pass


    def describe(self):
        print(f'3 layer neural network with {self.input_nodes} input nodes / {self.hidden_nodes} hidden nodes / {self.output_nodes} output nodes and learning rate {self.learning_rate}')
        print(f'{self.weight_input_hidden} \n {self.weight_hidden_output}')

In [59]:
n = NeuralNetwork(3,4,2,0.3)
n.describe()

3 layer neural network with 3 input nodes / 4 hidden nodes / 2 output nodes and learning rate 0.3
[[ 0.45537931 -0.00662479 -0.22398322]
 [-0.29955614 -0.24472533 -0.21153273]
 [ 0.3781836  -0.28204147  0.42888946]
 [-0.44754916 -0.11689778 -0.27178971]] 
 [[ 0.34196819 -0.34336187 -0.27501343 -0.30359261]
 [ 0.25488301 -0.33693796  0.44284689  0.03252393]]
